export type ReportDraft={text:string;region:string;category:string;risk:string};
export type Receipt={reference:string;accessKey:string;status:'Pending review';notificationSent?:boolean};
export type ReportReply={outcome:'accepted'|'duplicate'|'held';receipt:Receipt};
const base=(import.meta.env.VITE_REPORT_API_URL||'').trim().replace(/\/+$/,'');
export const reportingConnected=Boolean(base);
export class ReportServiceError extends Error {retryAfter:number;status:number;constructor(message:string,retryAfter=0,status=0){super(message);this.retryAfter=retryAfter;this.status=status}}
async function request(path:string,body:unknown,idempotencyKey?:string):Promise<Record<string,unknown>>{if(!base)throw new ReportServiceError('Reporting service is not connected yet.');const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),60000);try{const r=await fetch(base+path,{method:'POST',headers:{'Content-Type':'application/json',...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},body:JSON.stringify(body),credentials:'omit',cache:'no-store',signal:abort.signal});if(r.status===429){const seconds=Number(r.headers.get('Retry-After'));throw new ReportServiceError('Please wait before trying again.',Number.isFinite(seconds)&&seconds>0?seconds:60)}if(!r.ok)throw new ReportServiceError(r.status===404&&path==='/reports/track'?'The report reference or private access key is incorrect.':r.status===401?'Verification expired. Verify your contact again.':r.status===503?'Verification delivery is not configured. Please try later.':'Unable to complete this request. Please retry.',0,r.status);return await r.json()}finally{clearTimeout(timer)}}
export async function sendReportCode(channel:'sms'|'email',contact:string){const r=await request('/report-verifications',{channel,contact});if(typeof r.challengeId!=='string'||typeof r.maskedDestination!=='string')throw new ReportServiceError('Invalid verification response.');return {challengeId:r.challengeId,maskedDestination:r.maskedDestination,resendAfterSeconds:Math.max(30,Number(r.resendAfterSeconds)||60)}}
export async function verifyReportCode(challengeId:string,code:string){const r=await request('/report-verifications/confirm',{challengeId,code});if(typeof r.verificationToken!=='string'||!r.verificationToken)throw new ReportServiceError('Invalid verification response.');return r.verificationToken}
export async function submitProtectedReport(draft:ReportDraft,verificationToken:string,idempotencyKey:string):Promise<ReportReply>{const r=await request('/reports',{...draft,verificationToken},idempotencyKey);const receipt=r.receipt as Record<string,unknown>|undefined;if(!['accepted','duplicate','held'].includes(String(r.outcome))||!receipt||typeof receipt.reference!=='string'||typeof receipt.accessKey!=='string'||receipt.status!=='Pending review')throw new ReportServiceError('Invalid reporting response.');return r as unknown as ReportReply}

export type TrackingStep={id:string;label:string;at:string|null;state:'complete'|'current'|'pending'};
export type TrackedReport={reference:string;status:string;decision:string;submittedAt:string;updatedAt:string;area:string;category:string;concern:string;outcome:string;contactVerified:boolean;submissionFlag:string;nextStep:string;timeline:TrackingStep[]};
export async function trackProtectedReport(reference:string,accessKey:string):Promise<TrackedReport>{const r=await request('/reports/track',{reference,accessKey});const timeline=r.timeline;if(typeof r.reference!=='string'||typeof r.status!=='string'||typeof r.decision!=='string'||typeof r.submittedAt!=='string'||typeof r.updatedAt!=='string'||typeof r.area!=='string'||typeof r.category!=='string'||typeof r.concern!=='string'||typeof r.outcome!=='string'||typeof r.contactVerified!=='boolean'||typeof r.submissionFlag!=='string'||typeof r.nextStep!=='string'||!Array.isArray(timeline)||!timeline.every(step=>step&&typeof step==='object'&&typeof (step as Record<string,unknown>).id==='string'&&typeof (step as Record<string,unknown>).label==='string'&&['complete','current','pending'].includes(String((step as Record<string,unknown>).state))))throw new ReportServiceError('Invalid tracking response');return r as unknown as TrackedReport;}
