import {useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Camera,CheckCircle2,Clipboard,ExternalLink,FileImage,LifeBuoy,MessageCircle,ShieldCheck,X} from 'lucide-react';
import {useLanguage} from '../lib/i18n';
import {createSupportRequest,supportConnected} from '../lib/supportService';
import type {SupportCategory,SupportReceipt} from '../lib/supportService';

const categories:SupportCategory[]=['Message check','Report problem','Website problem','Accessibility','Other'];
const maxImageBytes=5*1024*1024;

export function Chat(){
  const {language}=useLanguage();const ta=language==='ta';const [params]=useSearchParams();
  const [category,setCategory]=useState<SupportCategory>(params.get('channel')==='whatsapp'?'Message check':'Website problem');
  const [description,setDescription]=useState('');const [reportReference,setReportReference]=useState('');const [image,setImage]=useState<File|null>(null);const [preview,setPreview]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [receipt,setReceipt]=useState<SupportReceipt|null>(null);const fileInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(!image){setPreview('');return;}const url=URL.createObjectURL(image);setPreview(url);return()=>URL.revokeObjectURL(url);},[image]);
  function acceptImage(file?:File){setError('');if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){setError(ta?'PNG, JPG அல்லது WebP படத்தை மட்டும் பயன்படுத்தவும்.':'Use a PNG, JPG or WebP image.');return;}if(file.size>maxImageBytes){setError(ta?'படம் 5 MB-க்கு குறைவாக இருக்க வேண்டும்.':'The image must be smaller than 5 MB.');return;}setImage(file);}
  function pasteImage(event:React.ClipboardEvent<HTMLDivElement>){const file=[...event.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){event.preventDefault();acceptImage(file);}}
  async function submit(event:React.FormEvent){event.preventDefault();if(busy)return;if(description.trim().length<10){setError(ta?'குறைந்தது 10 எழுத்துகளில் பிரச்சனையை விளக்கவும்.':'Describe the issue in at least 10 characters.');return;}setBusy(true);setError('');try{const next=await createSupportRequest({category,description:description.trim(),page:location.href,reportReference:reportReference.trim(),screenshot:image||undefined,channel:params.get('channel')==='whatsapp'?'whatsapp':'portal'});setReceipt(next);}catch(e){setError(e instanceof Error?e.message:'Unable to send request.');}finally{setBusy(false);}}
  const categoryLabel=(value:SupportCategory)=>ta?value==='Message check'?'சந்தேக செய்தியைச் சரிபார்க்க':value==='Report problem'?'புகார் தொடர்பான பிரச்சனை':value==='Website problem'?'இணையதளப் பிரச்சனை':value==='Accessibility'?'அணுகல் உதவி':'மற்ற உதவி':value;
  const whatsappText=receipt?`${ta?'ThoondilGuard உதவி கோரிக்கை':'ThoondilGuard support request'}\n${ta?'குறிப்பு':'Reference'}: ${receipt.reference}\n${ta?'வகை':'Category'}: ${categoryLabel(category)}\n${ta?'விவரம்':'Details'}: ${description.trim()}${image?`\n${ta?'Screenshot-ஐ இந்த chat-ல் தனியாக இணைக்கிறேன்.':'I will attach the screenshot separately in this chat.'}`:''}`:'';
  const whatsappNumber = import.meta.env.VITE_WHATSAPP_NUMBER || '+919876543210';
  const whatsappHref='https://wa.me/'+whatsappNumber.replace(/[^0-9]/g, '')+'?text='+encodeURIComponent(whatsappText);
  return <div className="mx-auto w-full max-w-4xl space-y-6">
    <div><span className="inline-flex items-center gap-2 rounded-full bg-teal-50 px-3 py-1 text-sm font-medium text-teal-800"><LifeBuoy size={17}/>{ta?'வழிகாட்டப்பட்ட உதவி':'Guided help'}</span><h1 className="mt-3 text-3xl font-semibold text-stone-950">{ta?'என்ன நடந்தது என்று சொல்லுங்கள்':'Tell us what happened'}</h1><p className="mt-2 max-w-2xl text-stone-600">{ta?'இது chatbot அல்ல. கேள்விகளின் வழியாக விவரங்களை ஒழுங்குபடுத்தி, நிர்வாகிக்கான உதவி கோரிக்கையை உருவாக்கும்.':'This is not a chatbot. It organises your details into a support request for the administrator.'}</p></div>
    {!receipt?<form onSubmit={submit} className="space-y-5">
      <section className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-semibold text-teal-800">{ta?'படி 1 / 3':'Step 1 of 3'}</p><h2 className="mt-1 text-xl font-semibold">{ta?'எந்த உதவி வேண்டும்?':'What do you need help with?'}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{categories.map(item=><button key={item} type="button" onClick={()=>setCategory(item)} aria-pressed={category===item} className={'min-h-12 rounded-xl border px-4 text-left font-medium '+(category===item?'border-teal-700 bg-teal-50 text-teal-900':'border-stone-200 bg-white text-stone-700')}>{categoryLabel(item)}</button>)}</div></section>
      <section className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-semibold text-teal-800">{ta?'படி 2 / 3':'Step 2 of 3'}</p><h2 className="mt-1 text-xl font-semibold">{ta?'விவரங்களையும் screenshot-ஐயும் சேர்க்கவும்':'Add details and a screenshot'}</h2><label className="mt-4 block font-medium">{ta?'என்ன தவறு நடந்தது?':'What went wrong?'}<textarea required minLength={10} maxLength={4000} value={description} onChange={e=>setDescription(e.target.value)} rows={5} placeholder={ta?'நீங்கள் என்ன செய்ய முயன்றீர்கள், என்ன நடந்தது என்பதை எழுதுங்கள்…':'Explain what you tried and what happened…'} className="mt-2 w-full rounded-xl border border-stone-300 p-3"/></label>{category==='Report problem'&&<label className="mt-4 block font-medium">{ta?'புகார் எண் (விருப்பம்)':'Report reference (optional)'}<input value={reportReference} onChange={e=>setReportReference(e.target.value)} maxLength={100} className="mt-2 min-h-12 w-full rounded-lg border border-stone-300 px-3"/></label>}
        <div onPaste={pasteImage} tabIndex={0} className="mt-4 rounded-xl border-2 border-dashed border-stone-300 bg-stone-50 p-5 focus:border-teal-700 focus:outline-none"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><Clipboard className="mt-1 text-teal-700"/><div><p className="font-semibold">{ta?'Screenshot-ஐ இங்கே paste செய்யவும்':'Paste a screenshot here'}</p><p className="mt-1 text-sm text-stone-600">{ta?'அல்லது PNG, JPG, WebP படத்தைத் தேர்வு செய்யவும்; அதிகபட்சம் 5 MB.':'Or choose a PNG, JPG or WebP image, up to 5 MB.'}</p></div></div><button type="button" onClick={()=>fileInput.current?.click()} className="min-h-11 rounded-lg border border-teal-700 bg-white px-4 font-medium text-teal-800"><Camera className="mr-2 inline" size={18}/>{ta?'படத்தைத் தேர்வு செய்':'Choose image'}</button></div><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" className="sr-only" onChange={e=>acceptImage(e.target.files?.[0])}/>{preview&&<div className="relative mt-4 w-fit"><img src={preview} alt={ta?'தேர்ந்தெடுத்த screenshot முன்னோட்டம்':'Selected screenshot preview'} className="max-h-64 rounded-lg border border-stone-200"/><button type="button" onClick={()=>setImage(null)} aria-label={ta?'படத்தை நீக்கு':'Remove image'} className="absolute right-2 top-2 rounded-full bg-black/75 p-2 text-white"><X size={16}/></button></div>}<p className="mt-3 text-xs text-stone-500">{ta?'இந்தப் படம் இப்போதைக்கு உங்கள் சாதனத்தில் மட்டுமே இருக்கும். WhatsApp திறந்த பிறகு அதை நீங்களே இணைக்க வேண்டும்.':'The image stays on this device. You must attach it yourself after WhatsApp opens.'}</p></div>
      </section>
      <section className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm font-semibold text-teal-800">{ta?'படி 3 / 3':'Step 3 of 3'}</p><h2 className="mt-1 text-xl font-semibold">{ta?'சரிபார்த்து அனுப்பவும்':'Review and send'}</h2><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">{ta?'வகை':'Category'}</dt><dd className="font-medium">{categoryLabel(category)}</dd></div><div><dt className="text-stone-500">{ta?'Screenshot':'Screenshot'}</dt><dd className="font-medium">{image?(ta?'தேர்ந்தெடுக்கப்பட்டது':'Selected'):(ta?'சேர்க்கப்படவில்லை':'Not added')}</dd></div></dl><button disabled={busy||!supportConnected} className="mt-5 min-h-12 rounded-lg bg-teal-700 px-6 font-semibold text-white disabled:opacity-50">{busy?(ta?'அனுப்புகிறது…':'Sending…'):(ta?'உதவி கோரிக்கையை உருவாக்கு':'Create support request')}</button>{!supportConnected&&<p className="mt-3 text-sm text-amber-800">{ta?'உதவி சேவை இன்னும் இணைக்கப்படவில்லை.':'The support service is not connected yet.'}</p>}</section>
    </form>:<section role="status" className="rounded-2xl border border-teal-200 bg-teal-50 p-6"><CheckCircle2 className="text-teal-700" size={36}/><h2 className="mt-3 text-2xl font-semibold">{ta?'உதவி கோரிக்கை பெறப்பட்டது':'Support request received'}</h2><p className="mt-2 text-stone-700">{ta?'இந்த குறிப்பு எண்ணை சேமிக்கவும்:':'Save this reference code:'}</p><p className="mt-3 break-all rounded-lg bg-white p-4 font-mono text-xl font-bold text-teal-900">{receipt.reference}</p><div className="mt-5 rounded-xl border border-emerald-200 bg-white p-4"><div className="flex gap-3"><MessageCircle className="text-emerald-700"/><div><h3 className="font-semibold">{ta?'WhatsApp-ல் தொடரவும்':'Continue in WhatsApp'}</h3><p className="mt-1 text-sm text-stone-600">{ta?'குறிப்பு எண்ணும் விவரமும் முன்பே நிரப்பப்படும். Screenshot இருந்தால் chat-ல் தனியாக இணைக்கவும்.':'The reference and details are prefilled. Attach the screenshot separately in the chat if you selected one.'}</p></div></div><a href={whatsappHref} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-700 px-5 font-semibold text-white">{ta?'WhatsApp திறக்க':'Open WhatsApp'}<ExternalLink size={17}/></a></div><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={()=>void navigator.clipboard.writeText(whatsappText)} className="min-h-11 rounded-lg border border-teal-700 bg-white px-4 text-teal-800"><FileImage className="mr-2 inline" size={17}/>{ta?'விவரங்களை copy செய்':'Copy request details'}</button><button type="button" onClick={()=>{setReceipt(null);setDescription('');setImage(null);setReportReference('');}} className="min-h-11 rounded-lg border border-stone-300 bg-white px-4">{ta?'மற்றொரு கோரிக்கை':'Another request'}</button></div></section>}
    {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}
    <p className="flex gap-2 text-sm text-stone-500"><ShieldCheck className="shrink-0" size={18}/>{ta?'Password, OTP, UPI PIN அல்லது வங்கி விவரங்களை எழுத வேண்டாம்.':'Do not include passwords, OTPs, UPI PINs or banking details.'}</p>
    <Link to="/check" className="inline-flex min-h-11 items-center text-teal-800 underline">{ta?'சந்தேக செய்தியைச் சரிபார்க்க':'Check a suspicious message'}</Link>
  </div>;
}
