import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useLanguage } from '../lib/i18n';
import { analyzeMessage, hasBackend } from '../lib/api';
import { redactPII } from '../lib/detector';
type Capture={image:string;title:string;url:string;domain:string;partial:boolean};
type Bridge={runtime:{sendMessage:(id:string,data:unknown,callback:(response:Capture&{ok:boolean;error?:string})=>void)=>void;lastError?:{message?:string}}};
export function PageAnalysis(){const {language}=useLanguage();const ta=language==='ta';const navigate=useNavigate();const once=useRef(false);const [capture,setCapture]=useState<Capture|null>(null);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [error,setError]=useState('');
useEffect(()=>{if(once.current)return;once.current=true;const params=new URLSearchParams(location.hash.slice(1));const id=params.get('extension'),token=params.get('token');const chrome=(window as unknown as {chrome?:Bridge}).chrome;if(!id||!token||!chrome?.runtime?.sendMessage){setError(ta?'நீட்டிப்பில் இருந்து இந்தப் பக்கத்தைத் திறக்கவும்.':'Open this page using Check this page in the browser extension.');return}setBusy(true);setStatus(ta?'ஸ்கிரீன்ஷாட்டைப் பெறுகிறது…':'Receiving screenshot…');chrome.runtime.sendMessage(id,{type:'getCapture',token},async r=>{const bridgeError=chrome.runtime.lastError;if(bridgeError||!r?.ok){setError(r?.error||'Could not receive capture. Reopen the extension and retry.');setBusy(false);return}history.replaceState(null,'',location.pathname);setCapture(r);let worker:Awaited<ReturnType<typeof import('tesseract.js').createWorker>>|undefined;try{setStatus(ta?'இந்த சாதனத்தில் உரையைப் படிக்கிறது…':'Reading text on this device…');const {createWorker}=await import('tesseract.js');worker=await createWorker('eng', 1, {workerPath: '/ocr/worker.min.js', corePath: '/ocr', langPath: '/ocr', gzip: false});const {data}=await worker.recognize(r.image);setText(data.text.trim());setStatus(ta?'உரையைப் பார்த்து சரிசெய்யவும்.':'Review and correct the extracted text before analysis.');if(!data.text.trim())setError('No readable text found. Paste the page text below.')}catch{setError(ta?'உரையைப் படிக்க முடியவில்லை. கீழே உரையை ஒட்டலாம்.':'OCR unavailable. Paste the page text below to continue.')}finally{await worker?.terminate();setBusy(false)}})},[ta]);
async function check(){setBusy(true);setError('');try{const input=[capture?.title,capture?.url,text].filter(Boolean).join('\n');const redactedText=redactPII(input);const result=await analyzeMessage(redactedText,language);navigate('/check/result',{state:{result,input,redactedText}})}catch{setError(ta?'சரிபார்க்க முடியவில்லை. மீண்டும் முயற்சி செய்யவும்.':'Analysis unavailable. Please retry.')}finally{setBusy(false)}}
return <div className="space-y-5"><Link to="/extension" className="text-teal-800 underline">← {ta?'உலாவி நீட்டிப்பு':'Browser extension'}</Link><h1 className="text-3xl font-semibold">{ta?'வலைப்பக்கத்தைச் சரிபார்க்க':'Analyze this page'}</h1>{capture&&<section className="rounded-xl border border-stone-200 bg-white p-5 space-y-3"><h2 className="font-semibold break-words">{capture.title}</h2><p className="text-sm break-all">{capture.domain} · {capture.url}</p>{capture.partial&&<p className="text-amber-800">{ta?'பக்கத்தின் ஒரு பகுதி மட்டும் படம்பிடிக்கப்பட்டது.':'Partial capture: this page exceeded the capture limit.'}</p>}<details><summary className="cursor-pointer text-teal-800">{ta?'ஸ்கிரீன்ஷாட்டைப் பார்க்க':'Review screenshot'}</summary><img src={capture.image} alt={ta?'படம்பிடிக்கப்பட்ட பக்கம்':'Captured page'} className="mt-3 w-full border rounded-lg"/></details></section>}<p role="status" className="text-stone-600">{status}</p>{error&&<p role="alert" className="text-red-700">{error}</p>}<label className="block font-medium">{ta?'படித்த உரை — திருத்தலாம்':'Extracted text — editable'}<textarea value={text} onChange={e=>setText(e.target.value)} disabled={busy} className="mt-2 w-full min-h-48 rounded-xl border border-stone-300 p-4"/></label><p className="text-sm text-stone-600">{ta?'தனிப்பட்ட தகவல்களை நீக்கி, உரையைச் சரிபார்த்த பிறகு தொடரவும்.':'Remove sensitive information and correct OCR mistakes before continuing.'} {hasBackend?'':'Local demo analysis until the backend is connected.'}</p><button disabled={busy||!text.trim()} onClick={()=>void check()} className="min-h-12 w-full rounded-full bg-teal-700 text-white disabled:opacity-40">{busy?(ta?'செயல்படுகிறது…':'Working…'):(ta?'சரிபார்த்து முடிவைப் பார்க்க':'Analyze and view full report')}</button></div>}
