import {useEffect,useRef,useState} from 'react';
import {Link,useLocation,useNavigate} from 'react-router-dom';
import {ArrowLeft,ShieldCheck,Clock,Copy,CheckCircle2,Mail,Smartphone} from 'lucide-react';
import {useLanguage} from '../lib/i18n';
import {redactPII} from '../lib/detector';
import {reportingConnected,sendReportCode,verifyReportCode,submitProtectedReport,ReportServiceError} from '../lib/reportService';
import type {ReportDraft,ReportReply} from '../lib/reportService';
const control='mt-2 w-full min-h-12 rounded-xl border border-stone-300 bg-stone-50 p-3 focus:outline-none focus:ring-2 focus:ring-teal-700';
export function ReportVerification(){const {language}=useLanguage();const ta=language==='ta';const location=useLocation();const navigate=useNavigate();const preview=location.pathname.endsWith('/preview');const draft=(location.state?.draft as ReportDraft|undefined);const [channel,setChannel]=useState<'sms'|'email'>('sms');const [contact,setContact]=useState('');const [code,setCode]=useState('');const [challenge,setChallenge]=useState('');const [destination,setDestination]=useState('');const [token,setToken]=useState('');const [step,setStep]=useState<'contact'|'code'|'review'>('contact');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [until,setUntil]=useState(0);const [now,setNow]=useState(()=>Date.now());const [resendUntil,setResendUntil]=useState(0);const [reply,setReply]=useState<ReportReply|null>(null);const [scenario,setScenario]=useState('contact');const [consent,setConsent]=useState(false);const [human,setHuman]=useState(false);
  const [captchaNum1, setCaptchaNum1] = useState(0);
  const [captchaNum2, setCaptchaNum2] = useState(0);
  const [captchaAnswer, setCaptchaAnswer] = useState('');
  useEffect(() => {
    setCaptchaNum1(Math.floor(Math.random() * 10) + 1);
    setCaptchaNum2(Math.floor(Math.random() * 10) + 1);
  }, []);
const idempotency=useRef(crypto.randomUUID());const locked=useRef(false);useEffect(()=>{if(!until&&!resendUntil)return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[until,resendUntil]);const remaining=Math.max(0,Math.ceil((until-now)/1000));const resendRemaining=Math.max(0,Math.ceil((resendUntil-now)/1000));
const contactValid=channel==='sms'?/^[0-9]{10}$/.test(contact):/^[^\s@]+@[^\s@.]+(?:\.[^\s@.]+)*\.[A-Za-z]{2,}$/.test(contact.trim());
function failure(e:unknown){if(e instanceof ReportServiceError&&e.status===401){setStep('contact');setToken('');setChallenge('');setCode('');}const seconds=e instanceof ReportServiceError?e.retryAfter:0;if(seconds){setUntil(Date.now()+seconds*1000);setNow(Date.now())}setError(e instanceof ReportServiceError?(ta?(seconds?'சிறிது நேரம் கழித்து மீண்டும் முயற்சி செய்யவும்.':'சேவையுடன் இணைக்க முடியவில்லை. மீண்டும் முயற்சி செய்யவும்.'):e.message):(ta?'இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சி செய்யவும்.':'Check your connection and retry.'))}
async function send(e:React.FormEvent){e.preventDefault();if(preview){if(!contactValid)return;setError('');setCode('');setScenario('code');return;}if(locked.current||remaining||resendRemaining||!contactValid)return;locked.current=true;setBusy(true);setError('');try{const result=await sendReportCode(channel,channel==='sms'?'+91'+contact:contact.trim());setChallenge(result.challengeId);setDestination(result.maskedDestination);setResendUntil(Date.now()+result.resendAfterSeconds*1000);setNow(Date.now());setStep('code')}catch(e){failure(e)}finally{locked.current=false;setBusy(false)}}
async function verify(e:React.FormEvent){e.preventDefault();if(preview){if(code!=='123456'){setError(ta?'முன்னோட்டத்திற்கு 123456 உள்ளிடவும்.':'For this preview, enter 123456.');return;}setError('');setConsent(false);setScenario('review');return;}if(locked.current||remaining)return;locked.current=true;setBusy(true);setError('');try{setToken(await verifyReportCode(challenge,code));setStep('review');setCode('')}catch(e){failure(e)}finally{locked.current=false;setBusy(false)}}
async function submit(){if(preview){if(consent){setError('');setScenario('accepted');}return;}if(!draft||locked.current||remaining||!consent)return;locked.current=true;setBusy(true);setError('');try{const result=await submitProtectedReport({...draft,text:redactPII(draft.text)},token,idempotency.current);setReply(result);setContact('');setCode('');setToken('')}catch(e){failure(e)}finally{locked.current=false;setBusy(false)}}
const selected=preview?scenario:reply?reply.outcome:remaining?'cooldown':step;
const sampleDraft={text:ta?'உங்கள் மின்சார கட்டணத்தை உடனே செலுத்துங்கள். [PHONE REDACTED]':'Pay your electricity bill immediately. [PHONE REDACTED]',region:'Velachery',category:'Electricity Bill Scam',risk:'Needs verification'};
const shownDraft=draft||sampleDraft;const shownReceipt=reply?.receipt;
if(!preview&&!draft)return <div className="space-y-5"><h1 className="text-3xl font-semibold">{ta?'முதலில் புகாரைத் தயாரிக்கவும்':'Prepare your report first'}</h1><Link to="/report" className="text-teal-800 underline">{ta?'புகார் அளிக்க':'Report a message'}</Link></div>;
return <div className="mx-auto max-w-2xl space-y-6"><Link to="/report" state={draft?{text:draft.text}:undefined} className="inline-flex min-h-11 items-center gap-2 text-teal-800"><ArrowLeft size={18}/>{ta?'புகாருக்குத் திரும்பு':'Back to report'}</Link>{preview&&<><p className="text-sm text-stone-500">{ta?'திரை முன்னோட்டம் மட்டும் — குறியீடும் புகாரும் அனுப்பப்படாது.':'Interface preview — no code or report is sent.'}</p><div className="flex flex-wrap gap-2" aria-label="Submission screens">{[['contact','Contact','தொடர்பு'],['code','Verification','சரிபார்ப்பு'],['review','Review','மறுபார்வை'],['accepted','Received','பெறப்பட்டது'],['duplicate','Duplicate','ஏற்கெனவே உள்ளது'],['held','Under review','சரிபார்ப்பில்'],['cooldown','Wait','காத்திரு']].map(([value,en,tamil])=><button key={value} onClick={()=>{setScenario(value);setError('')}} aria-pressed={scenario===value} className={'min-h-11 rounded-full border px-4 text-sm '+(scenario===value?'bg-teal-700 text-white border-teal-700':'bg-white border-stone-200')}>{ta?tamil:en}</button>)}</div></>}
<section className="rounded-2xl border border-stone-200 bg-white p-5 sm:p-8 shadow-sm">
{selected==='contact'&&<><div className="flex gap-3 items-center mb-4"><ShieldCheck className="text-teal-700"/><h1 className="text-2xl font-semibold">{ta?'உங்கள் தொடர்பைச் சரிபார்க்கவும்':'Verify your contact'}</h1></div><p className="text-stone-600 mb-6">{ta?'தொலைபேசி அல்லது மின்னஞ்சலில் ஒரு குறியீடு மூலம் சரிபார்க்கலாம். இரண்டும் தேவையில்லை.':'Use a code sent to your phone or email. You only need one.'}</p><div className="flex gap-3 mb-5">{(['sms','email'] as const).map(c=><button key={c} onClick={()=>{setChannel(c);setContact('');setChallenge('');setToken('');setConsent(false)}} aria-pressed={channel===c} className={'min-h-11 flex-1 flex items-center justify-center gap-2 rounded-lg border '+(channel===c?'border-teal-700 bg-teal-50 text-teal-800':'border-stone-200')}>{c==='sms'?<Smartphone size={18}/>:<Mail size={18}/>} {c==='sms'?(ta?'தொலைபேசி':'Phone'):(ta?'மின்னஞ்சல்':'Email')}</button>)}</div><form onSubmit={send}><label htmlFor="verify-contact" className="block font-medium">{channel==='sms'?(ta?'மொபைல் எண்':'Mobile number'):(ta?'மின்னஞ்சல் முகவரி':'Email address')}</label><div className="mt-2 flex items-stretch overflow-hidden rounded-xl border border-stone-300 bg-stone-50 focus-within:ring-2 focus-within:ring-teal-700">{channel==='sms'&&<span className="flex items-center border-r border-stone-300 px-4 font-medium" aria-label="India country code">+91</span>}<input id="verify-contact" required type={channel==='sms'?'tel':'email'} inputMode={channel==='sms'?'numeric':'email'} autoComplete={channel==='sms'?'tel-national':'email'} maxLength={channel==='sms'?10:254} pattern={channel==='sms'?'[0-9]{10}':undefined} value={contact} onChange={e=>setContact(channel==='sms'?e.target.value.replace(/\D/g,'').slice(0,10):e.target.value)} className="min-h-12 min-w-0 flex-1 bg-transparent p-3 outline-none" placeholder={channel==='sms'?'9876543210':'you@example.com'}/></div><p className="mt-2 text-sm text-stone-500">{channel==='sms'?(ta?'10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.':'Enter your 10-digit mobile number.'):(ta?'முழுமையான மின்னஞ்சல் முகவரியை உள்ளிடவும்.':'Enter a complete email address, such as name@example.com.')}</p><p className="mt-3 text-sm text-stone-500">{ta?'தொடர்பு விவரம் பொதுமக்களுக்குக் காட்டப்படாது.':'Your contact details will not be displayed publicly.'}</p><button disabled={busy||(!preview&&!reportingConnected)||!contactValid} className="mt-6 min-h-12 w-full rounded-full bg-teal-700 text-white font-semibold disabled:opacity-50">{busy?(ta?'அனுப்புகிறது…':'Sending…'):(ta?'குறியீட்டை அனுப்பு':'Send verification code')}</button></form>{!preview&&!reportingConnected&&<p role="status" className="mt-4 text-sm text-stone-600">{ta?'சரிபார்ப்பு சேவை இன்னும் இணைக்கப்படவில்லை.':'Verification service is not connected yet.'}</p>}</>}
{selected==='code'&&<><h1 className="text-2xl font-semibold">{ta?'குறியீட்டை உள்ளிடவும்':'Enter verification code'}</h1><p className="mt-3 text-stone-600">{preview?(ta?'முன்னோட்டக் குறியீடு: 123456. SMS அல்லது email அனுப்பப்படாது.':'Preview code: 123456. No SMS or email is sent.'):destination}</p><form onSubmit={verify} className="mt-6"><label htmlFor="verification-code" className="block font-medium">{ta?'6 இலக்க குறியீடு':'6-digit code'}</label><input id="verification-code" required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className={control+' text-xl tracking-[.3em]'} placeholder="••••••"/><button disabled={busy||code.length!==6} className="mt-5 min-h-12 w-full rounded-full bg-teal-700 text-white font-semibold disabled:opacity-50">{ta?'சரிபார்த்து தொடரவும்':'Verify and continue'}</button></form><div className="mt-4 flex flex-wrap justify-between gap-3"><button disabled={busy} onClick={()=>{if(preview)setScenario('contact');setStep('contact');setCode('');setChallenge('');setResendUntil(0)}} className="min-h-11 text-teal-800 underline">{ta?'தொடர்பை மாற்று':'Change contact'}</button><button disabled={busy||resendRemaining>0} onClick={()=>void send({preventDefault(){}} as React.FormEvent)} className="min-h-11 text-teal-800 underline disabled:text-stone-400">{ta?'மீண்டும் அனுப்பு':'Resend code'}{resendRemaining>0?' · '+resendRemaining+'s':''}</button></div></>}
{selected==='review'&&<><h1 className="text-2xl font-semibold">{ta?'புகாரைப் பார்த்து உறுதிசெய்யவும்':'Review and confirm'}</h1><p className="mt-3 text-stone-600">{ta?'தனிப்பட்ட தகவல்கள் மறைக்கப்பட்டுள்ளதா என்று பாருங்கள்.':'Check that personal details are masked before submitting.'}</p><div className="mt-5 rounded-xl bg-stone-50 border border-stone-200 p-4 whitespace-pre-wrap break-words">{redactPII(shownDraft.text)}</div><p className="mt-3 text-sm text-stone-600">{shownDraft.region} · {shownDraft.category}</p><label className="mt-5 flex gap-3 items-start text-sm"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)} className="mt-1 h-4 w-4 accent-teal-700"/>{ta?'இந்த முன்னோட்டத்தைச் சரிபார்த்தேன். நிர்வாகி சரிபார்ப்பிற்குப் புகாரை அனுப்ப ஒப்புக்கொள்கிறேன்.':'I have checked the preview and agree to submit it for administrator review.'}</label><div className="mt-5 flex flex-col gap-2">
  <label htmlFor="captcha-input" className="block text-sm text-stone-600 font-medium">
    {ta ? `?????? ?????? ?????????????????: ${captchaNum1} + ${captchaNum2} = ?` : `Verify you are human: ${captchaNum1} + ${captchaNum2} = ?`}
  </label>
  <div className="flex gap-3 items-center">
    <input
      id="captcha-input"
      type="number"
      value={captchaAnswer}
      onChange={e => {
        setCaptchaAnswer(e.target.value);
        setHuman(parseInt(e.target.value, 10) === captchaNum1 + captchaNum2);
      }}
      className="min-h-12 w-24 p-3 rounded-lg border border-stone-300 bg-stone-50 focus:ring-2 focus:ring-teal-700 outline-none text-center text-lg"
    />
    {human && <CheckCircle2 className="text-teal-700" size={24}/>}
  </div>
</div><button disabled={busy||!consent||!human} onClick={()=>void submit()} className="mt-6 min-h-12 w-full rounded-full bg-teal-700 text-white font-semibold disabled:opacity-50">{busy?(ta?'சமர்ப்பிக்கப்படுகிறது...':'Submitting...'):(ta?'புகாரை உறுதிப்படுத்து':'Confirm report')}</button></>}
{['accepted','duplicate','held'].includes(selected)&&<><div className="flex gap-3 items-center"><CheckCircle2 className="text-teal-700 shrink-0"/><h1 className="text-2xl font-semibold">{selected==='duplicate'?(ta?'இந்தப் புகார் ஏற்கெனவே உள்ளது':'This report already exists'):selected==='held'?(ta?'புகார் சரிபார்ப்பிற்காக வைக்கப்பட்டுள்ளது':'Report held for review'):(ta?'உங்கள் புகார் பெறப்பட்டது':'Your report is received')}</h1></div><p className="mt-4 text-stone-600">{selected==='duplicate'?(ta?'புதிய புகார் உருவாக்கப்படவில்லை. ஏற்கெனவே உள்ள புகாரைக் கண்காணிக்கவும்.':'No extra report was created. Track your existing submission below.'):(ta?'நிர்வாகி ஆதாரத்தைச் சரிபார்ப்பார். இது தானாகப் பொது எச்சரிக்கையாக வெளியிடப்படாது.':'An administrator will review the evidence. This does not automatically publish a community alert.')}</p><dl className="mt-6 space-y-4"><div><dt className="text-sm text-stone-500">{ta?'புகார் எண்':'Report reference'}</dt><dd className="mt-1 rounded-lg border border-stone-200 p-3 font-mono break-all select-all">{shownReceipt?.reference||'TG-EXAMPLE'}</dd></div><div><dt className="text-sm text-stone-500">{ta?'தனிப்பட்ட அணுகல் சாவி':'Private access key'}</dt><dd className="mt-1 rounded-lg border border-stone-200 p-3 font-mono break-all select-all">{shownReceipt?.accessKey||'•••• •••• •••• ••••'}</dd></div></dl><p className="mt-4 text-sm text-stone-600">{ta?'இரண்டையும் பாதுகாப்பாகச் சேமியுங்கள்; சாவியைப் பகிர வேண்டாம்.':'Save both values securely. Do not share your access key.'}</p><div className="mt-6 flex flex-wrap gap-3"><button disabled={preview} onClick={()=>{if(shownReceipt)void navigator.clipboard.writeText(shownReceipt.reference+'\n'+shownReceipt.accessKey).then(()=>setError(ta?'நகலெடுக்கப்பட்டது':'Copied')).catch(()=>setError(ta?'கைமுறையாக நகலெடுக்கவும்':'Select and copy the values manually.'))}} className="min-h-11 flex gap-2 items-center border border-stone-300 rounded-lg px-4 disabled:opacity-50"><Copy size={16}/>{ta?'விவரங்களை நகலெடு':'Copy details'}</button><button disabled={preview} onClick={()=>navigate('/track',{state:{reference:shownReceipt?.reference}})} className="min-h-11 rounded-lg bg-teal-700 text-white px-5 disabled:opacity-50">{ta?'புகாரைக் கண்காணி':'Track report'}</button></div></>}
{selected==='cooldown'&&<><Clock className="text-amber-700 mb-4" size={32}/><h1 className="text-2xl font-semibold">{ta?'சிறிது நேரம் காத்திருக்கவும்':'Please wait before trying again'}</h1><p className="mt-4 text-stone-600">{ta?'குறுகிய நேரத்தில் பல முயற்சிகள் வந்துள்ளன. உங்கள் புகார் விவரங்கள் இங்கே பாதுகாக்கப்பட்டுள்ளன.':'There have been several attempts in a short time. Your report details are still here.'}</p><p role="status" className="mt-5 font-semibold text-amber-800">{preview?(ta?'1 நிமிடம் கழித்து மீண்டும் முயற்சி செய்யவும்':'Try again in 1 minute'):(ta?'மீதமுள்ள விநாடிகள்: ':'Seconds remaining: ')+remaining}</p><button disabled={preview||remaining>0} onClick={()=>{setUntil(0);setError('')}} className="mt-5 min-h-12 rounded-lg bg-teal-700 text-white px-5 disabled:opacity-50">{ta?'மீண்டும் முயற்சி செய்':'Try again'}</button></>}
{error&&selected!=='cooldown'&&<p role="alert" className="mt-4 text-red-700">{error}</p>}
</section></div>}
