import { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Clock3, KeyRound, ShieldCheck } from 'lucide-react';
import { useLanguage } from '../lib/i18n';
import { reportingConnected, trackProtectedReport } from '../lib/reportService';
import type { TrackedReport } from '../lib/reportService';

function statusText(value:string,ta:boolean){if(value==='New')return ta?'பெறப்பட்டது':'Received';if(value==='In progress')return ta?'நிர்வாகி சரிபார்க்கிறார்':'Under administrator review';if(value==='Closed')return ta?'முடிவு பதிவு செய்யப்பட்டது':'Decision recorded';return value;}
function decisionText(value:string,ta:boolean){if(value==='Pending')return ta?'முடிவு நிலுவையில் உள்ளது':'Decision pending';if(value==='Suspicious')return ta?'சந்தேகத்திற்குரியது என உறுதி செய்யப்பட்டது':'Confirmed suspicious';if(value==='Insufficient evidence')return ta?'போதுமான ஆதாரம் இல்லை':'Insufficient evidence';if(value==='No concern identified')return ta?'கவலைக்குரிய ஆதாரம் கண்டறியப்படவில்லை':'No concern identified';return value;}
function concernText(value:string,ta:boolean){if(!ta)return value;return value==='High concern'?'அதிக கவலை':value==='Needs verification'?'மேலும் சரிபார்ப்பு தேவை':value==='No strong warning signs found'?'வலுவான எச்சரிக்கை அறிகுறிகள் இல்லை':'மதிப்பீடு நிலுவையில் உள்ளது';}
function stepText(value:string,ta:boolean){if(!ta)return value;return value==='Report received'?'புகார் பெறப்பட்டது':value==='Contact verified'?'தொடர்பு சரிபார்க்கப்பட்டது':value==='Administrator review'?'நிர்வாகி சரிபார்ப்பு':'முடிவு பதிவு';}
function nextStepText(result:TrackedReport,ta:boolean){if(!ta)return result.nextStep;if(result.status==='New')return 'உங்கள் புகார் பாதுகாப்பாக பதிவு செய்யப்பட்டு நிர்வாகி சரிபார்ப்புக்காக காத்திருக்கிறது.';if(result.status==='In progress')return 'நிர்வாகி ஆதாரத்தை சரிபார்க்கிறார். அடுத்த புதுப்பிப்பைப் பார்க்க உங்கள் புகார் எண் மற்றும் தனிப்பட்ட சாவியை வைத்திருங்கள்.';if(result.decision==='Suspicious')return 'இந்த புகார் சந்தேகத்திற்குரியது என உறுதி செய்யப்பட்டுள்ளது. வெளியிடப்பட்ட பாதுகாப்பு வழிகாட்டுதலைப் பின்பற்றி அனுப்புநருடன் மேலும் தொடர்பு கொள்ள வேண்டாம்.';if(result.decision==='Insufficient evidence')return 'உறுதி செய்ய போதுமான ஆதாரம் இல்லை. மேலும் தகவல் கிடைத்தால் பயன்படுத்த அசல் செய்தி அல்லது screenshot-ஐ வைத்திருங்கள்.';return 'கிடைத்த ஆதாரத்தில் கவலை உறுதி செய்யப்படவில்லை. ஏதேனும் மாற்றம் இருந்தால் அதிகாரப்பூர்வ வழிகளைப் பயன்படுத்தவும்.';}
function normalizeProgress(value:TrackedReport):TrackedReport{const closed=value.status==='Closed'||value.decision!=='Pending';return {...value,status:closed?'Closed':value.status,timeline:value.timeline.map(step=>step.id==='review'?{...step,state:closed?'complete':'current'}:step.id==='decision'?{...step,state:closed?'complete':'pending',at:closed?value.updatedAt:null}:step)};}

export function TrackReport(){
  const {language}=useLanguage();const ta=language==='ta';const location=useLocation();
  const [reference,setReference]=useState(location.state?.reference||'');const [key,setKey]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<TrackedReport|null>(null);const [activeLookup,setActiveLookup]=useState<{reference:string;key:string}|null>(null);const [lastChecked,setLastChecked]=useState<Date|null>(null);
  async function retrieve(ref:string,secret:string,firstLookup=false){if(busy)return;setBusy(true);setError('');if(firstLookup)setResult(null);try{if(!reportingConnected)throw Error(ta?'கண்காணிப்பு சேவை இன்னும் இணைக்கப்படவில்லை.':'Tracking service is not connected yet.');const next=normalizeProgress(await trackProtectedReport(ref,secret));setResult(next);setLastChecked(new Date());if(firstLookup){setActiveLookup({reference:ref,key:secret});setKey('');}}catch(e){setError(e instanceof Error?e.message:'Could not retrieve report');}finally{setBusy(false);}}
  async function lookup(e:React.FormEvent){e.preventDefault();await retrieve(reference.trim(),key.trim(),true);}
  useEffect(()=>{if(!activeLookup)return;const timer=window.setInterval(()=>{void trackProtectedReport(activeLookup.reference,activeLookup.key).then(next=>{setResult(normalizeProgress(next));setLastChecked(new Date());setError('');}).catch(()=>{});},30000);return()=>window.clearInterval(timer);},[activeLookup]);
  const locale=ta?'ta-IN':'en-IN';
  return <div className="mx-auto max-w-5xl space-y-7">
    <Link to="/report" className="inline-flex min-h-11 items-center gap-2 text-teal-800"><ArrowLeft size={18}/>{ta?'புகார் அளிக்க':'Report a message'}</Link>
    <div><h1 className="text-3xl font-semibold text-stone-950">{ta?'புகாரின் நிலையை அறிய':'Track your report'}</h1><p className="mt-2 text-stone-600">{ta?'புகார் எண் மற்றும் தனிப்பட்ட அணுகல் சாவியை உள்ளிடுங்கள்.':'Enter your report reference and private access key.'}</p></div>
    <form onSubmit={lookup} className="grid gap-4 rounded-2xl border border-stone-200 bg-white p-5 shadow-sm md:grid-cols-[1fr_1fr_auto] md:items-end">
      <label className="block font-medium">{ta?'புகார் எண்':'Report reference'}<input required value={reference} onChange={e=>setReference(e.target.value)} className="mt-2 min-h-12 w-full rounded-lg border border-stone-300 px-3"/></label>
      <label className="block font-medium">{ta?'தனிப்பட்ட அணுகல் சாவி':'Private access key'}<span className="relative mt-2 block"><KeyRound aria-hidden className="absolute left-3 top-3.5 text-stone-400" size={19}/><input required type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} className="min-h-12 w-full rounded-lg border border-stone-300 pl-10 pr-3"/></span></label>
      <button disabled={busy||!reportingConnected} className="min-h-12 rounded-lg bg-teal-700 px-5 font-medium text-white disabled:opacity-50">{busy?(ta?'தேடுகிறது…':'Checking…'):(ta?'நிலையைப் பார்க்க':'Check status')}</button>
    </form>
    {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-4 text-red-800">{error}</p>}
    {result&&<section aria-labelledby="tracking-title" className="space-y-5">
      <div className="flex flex-col gap-4 rounded-2xl border border-teal-200 bg-teal-50 p-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium text-teal-800">{ta?'தற்போதைய நிலை':'Current status'}</p><h2 id="tracking-title" className="mt-1 text-2xl font-semibold text-stone-950">{statusText(result.status,ta)}</h2><p className="mt-2 text-stone-700">{decisionText(result.decision,ta)}</p>{lastChecked&&<p className="mt-2 text-xs text-stone-500">{ta?'கடைசியாக சரிபார்க்கப்பட்டது':'Last checked'}: {lastChecked.toLocaleTimeString(locale)}</p>}</div><div className="flex flex-wrap items-center gap-2"><span className="inline-flex w-fit items-center gap-2 rounded-full bg-white px-3 py-2 text-sm font-medium text-teal-800"><ShieldCheck size={18}/>{result.contactVerified?(ta?'தொடர்பு சரிபார்க்கப்பட்டது':'Contact verified'):(ta?'சரிபார்ப்பு நிலுவையில்':'Verification pending')}</span>{activeLookup&&<button type="button" disabled={busy} onClick={()=>void retrieve(activeLookup.reference,activeLookup.key)} className="min-h-10 rounded-full border border-teal-700 bg-white px-4 text-sm font-medium text-teal-800 disabled:opacity-50">{busy?(ta?'புதுப்பிக்கிறது…':'Refreshing…'):(ta?'நிலையைப் புதுப்பிக்க':'Refresh status')}</button>}</div></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        {[{label:ta?'புகார் எண்':'Reference',value:result.reference},{label:ta?'சமர்ப்பிக்கப்பட்டது':'Submitted',value:new Date(result.submittedAt).toLocaleString(locale)},{label:ta?'பகுதி':'Area',value:result.area||'—'},{label:ta?'வகை':'Category',value:result.category||'—'}].map(item=><div key={item.label} className="rounded-xl border border-stone-200 bg-white p-4"><p className="text-sm text-stone-500">{item.label}</p><p className="mt-1 break-words font-semibold text-stone-900">{item.value}</p></div>)}
      </div>
      <div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
        <div className="rounded-2xl border border-stone-200 bg-white p-5"><h3 className="font-semibold text-stone-950">{ta?'முன்னேற்றம்':'Progress'}</h3><ol className="mt-5 space-y-5">{result.timeline.map((step,index)=><li key={step.id} className="flex gap-3"><div className="flex flex-col items-center">{step.state==='complete'?<CheckCircle2 className="text-teal-700" size={22}/>:<Clock3 className={step.state==='current'?'text-amber-600':'text-stone-300'} size={22}/>} {index<result.timeline.length-1&&<span className="mt-1 h-8 w-px bg-stone-200"/>}</div><div><p className={step.state==='pending'?'text-stone-400':'font-medium text-stone-900'}>{stepText(step.label,ta)}</p>{step.at&&<p className="mt-1 text-sm text-stone-500">{new Date(step.at).toLocaleString(locale)}</p>}</div></li>)}</ol></div>
        <div className="space-y-4"><div className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-sm text-stone-500">{ta?'ஆரம்ப மதிப்பீடு':'Initial assessment'}</p><p className="mt-1 font-semibold text-stone-900">{concernText(result.concern,ta)}</p><p className="mt-4 text-sm text-stone-500">{ta?'கடைசியாக புதுப்பிக்கப்பட்டது':'Last updated'}</p><p className="mt-1 text-stone-800">{new Date(result.updatedAt).toLocaleString(locale)}</p></div><div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-semibold text-blue-950">{ta?'அடுத்து என்ன செய்ய வேண்டும்':'What to do next'}</h3><p className="mt-2 leading-7 text-blue-950">{nextStepText(result,ta)}</p></div>{result.submissionFlag&&<p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-900">{result.submissionFlag}</p>}</div>
      </div>
      <p className="text-sm text-stone-500">{ta?'நிர்வாகியின் உள் குறிப்புகள் மற்றும் தனிப்பட்ட தொடர்பு தகவல்கள் இந்தப் பக்கத்தில் காட்டப்படாது.':'Internal administrator notes and private contact details are not shown on this page.'}</p>
    </section>}
  </div>;
}
