const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function run(tabId,func,args=[]){const r=await chrome.scripting.executeScript({target:{tabId},func,args});return r[0].result}
async function capture(tabId,windowId){const {portal}=await chrome.storage.local.get('portal');if(!portal)throw Error('Set your portal address first.');const tab=await chrome.tabs.get(tabId);if(!/^https?:/.test(tab.url))throw Error('This page cannot be captured.');let initial;try{
initial=await run(tabId,()=>{const e=document.documentElement;const v={x:scrollX,y:scrollY,w:innerWidth,h:innerHeight,height:Math.max(e.scrollHeight,document.body?.scrollHeight||0),behavior:e.style.scrollBehavior};e.style.scrollBehavior='auto';return v});
const height=Math.min(initial.height,16000,initial.h*24);let canvas,ctx,scale,lastEnd=0;const started=Date.now();
for(let y=0;y<height;y+=initial.h){if(Date.now()-started>24000)throw Error('Page is too long. Try a shorter page.');const [{id}]=await chrome.tabs.query({active:true,windowId});if(id!==tabId)throw Error('Capture stopped because the active tab changed.');const pos=await run(tabId,y=>{scrollTo(0,y);return {x:scrollX,y:scrollY}},[y]);await pause(600);const data=await chrome.tabs.captureVisibleTab(windowId,{format:'png'});const [current]=await chrome.tabs.query({active:true,windowId});if(current.id!==tabId)throw Error('Capture stopped because the active tab changed.');const bitmap=await createImageBitmap(await (await fetch(data)).blob());if(!canvas){scale=bitmap.width/initial.w;const targetHeight=Math.ceil(height*scale);if(bitmap.width*targetHeight>40000000)throw Error('Page image is too large. Reduce browser zoom and retry.');canvas=new OffscreenCanvas(bitmap.width,targetHeight);ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height)}const dest=Math.round(pos.y*scale);const skip=Math.max(0,lastEnd-dest);const take=Math.min(bitmap.height-skip,canvas.height-dest-skip);if(take>0){ctx.drawImage(bitmap,0,skip,bitmap.width,take,0,dest+skip,bitmap.width,take);lastEnd=dest+skip+take}bitmap.close();if(lastEnd>=canvas.height)break}
const blob=await canvas.convertToBlob({type:'image/jpeg',quality:.85});if(blob.size>7*1024*1024)throw Error('Capture is too large. Try a shorter page.');const bytes=new Uint8Array(await blob.arrayBuffer());let bin='';for(let i=0;i<bytes.length;i+=8192)bin+=String.fromCharCode(...bytes.subarray(i,i+8192));const image='data:image/jpeg;base64,'+btoa(bin);const token=crypto.randomUUID();const destination=await chrome.tabs.create({url:'about:blank',active:false});await chrome.storage.local.set({['capture:'+token]:{title:tab.title,url:tab.url,domain:new URL(tab.url).hostname,image,partial:height<initial.height,expires:Date.now()+5*60000,portal,tabId:destination.id}});await chrome.tabs.update(destination.id,{url:portal+'/analyze#'+new URLSearchParams({extension:chrome.runtime.id,token}),active:true});return {ok:true};
}finally{if(initial)await run(tabId,(v)=>{document.documentElement.style.scrollBehavior='auto';scrollTo(v.x,v.y);document.documentElement.style.scrollBehavior=v.behavior},[initial]).catch(()=>{})}}
chrome.runtime.onMessage.addListener((m,s,reply)=>{if(s.id!==chrome.runtime.id||m.type!=='capture')return;capture(m.tabId,m.windowId).then(reply).catch(e=>reply({ok:false,error:e.message||'Capture failed.'}));return true});
chrome.runtime.onMessageExternal.addListener((m,s,reply)=>{if(m.type!=='getCapture'||typeof m.token!=='string')return;const key='capture:'+m.token;(async()=>{const data=(await chrome.storage.local.get(key))[key];if(!data||Date.now()>data.expires||s.tab?.id!==data.tabId||new URL(s.url).origin!==data.portal)return reply({ok:false,error:'Capture expired or unavailable.'});await chrome.storage.local.remove(key);const {image,title,url,domain,partial}=data;reply({ok:true,image,title,url,domain,partial})})().catch(()=>reply({ok:false,error:'Capture unavailable.'}));return true});
async function cleanup(){const all=await chrome.storage.local.get(null);await chrome.storage.local.remove(Object.keys(all).filter(k=>k.startsWith('capture:')&&all[k].expires<Date.now()))}chrome.runtime.onStartup.addListener(()=>void cleanup());void cleanup();
