import {useEffect,useState} from 'react';
import {LifeBuoy,RefreshCw} from 'lucide-react';
import {adminConnected,adminRequest,adminBase} from '../lib/adminApi';
import {useLanguage} from '../lib/languageState';

type SupportRequest={id:string;category:string;description:string;page:string;reportReference:string;screenshotAttached:boolean;screenshotUrl?:string;channel:string;status:'New'|'In progress'|'Resolved';adminNote:string;createdAt:string;updatedAt:string};
export function SupportRequests(){const {t}=useLanguage();const [items,setItems]=useState<SupportRequest[]>([]);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  async function load(){if(!adminConnected)return;setLoading(true);setError('');try{const response=await adminRequest('/support-requests') as {requests?:SupportRequest[]};if(!Array.isArray(response.requests))throw Error('Invalid support response');setItems(response.requests);}catch(e){setError(e instanceof Error?e.message:'Unable to load support requests');}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function update(item:SupportRequest,status:SupportRequest['status']){const note=window.prompt(t('Administrator note'),item.adminNote||'')??item.adminNote;try{await adminRequest('/support-requests/'+encodeURIComponent(item.id),'PATCH',{status,adminNote:note});await load();}catch(e){setError(e instanceof Error?e.message:'Unable to update request');}}
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><LifeBuoy/><h1>{t('Support requests')}</h1></div><p className="mt-2 text-text-secondary">{t('Guided help requests submitted from the resident portal.')}</p></div><button className="secondary" disabled={loading} onClick={()=>void load()}><RefreshCw size={17}/>{t('Refresh')}</button></div>{error&&<p role="alert" className="text-status-red-text">{error}</p>}{!adminConnected&&<p>{t('Connect the backend to view support requests.')}</p>}{adminConnected&&!loading&&items.length===0&&<div className="panel"><h2>{t('No support requests')}</h2><p className="mt-2 text-text-secondary">{t('New requests will appear here.')}</p></div>}<div className="grid gap-4">{items.map(item=><article key={item.id} className="panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-text-secondary">{item.id}</p><h2 className="mt-1">{item.category}</h2><p className="mt-2 max-w-4xl whitespace-pre-wrap">{item.description}</p></div><span className="status-badge">{item.status}</span></div><dl className="mt-4 grid gap-3 text-sm md:grid-cols-4"><div><dt className="text-text-secondary">{t('Submitted')}</dt><dd>{new Date(item.createdAt).toLocaleString('en-IN')}</dd></div><div><dt className="text-text-secondary">{t('Channel')}</dt><dd>{item.channel}</dd></div><div><dt className="text-text-secondary">{t('Report reference')}</dt><dd>{item.reportReference||'—'}</dd></div><div><dt className="text-text-secondary">{t('Screenshot')}</dt><dd className="flex items-center gap-1">{item.screenshotUrl?<a href={adminBase+'/attachments/'+encodeURIComponent(item.screenshotUrl.split('/').pop()||'')} target="_blank" rel="noreferrer" className="text-blue-600 underline">View attached screenshot</a>:item.screenshotAttached?t('Attached via WhatsApp'):t('Not selected')}</dd></div></dl>{item.adminNote&&<p className="mt-4 rounded-lg bg-panel-alt p-3 text-sm"><strong>{t('Administrator note')}:</strong> {item.adminNote}</p>}<div className="mt-4 flex flex-wrap gap-2"><button className="secondary" onClick={()=>void update(item,'In progress')}>{t('Mark in progress')}</button><button className="primary" onClick={()=>void update(item,'Resolved')}>{t('Mark resolved')}</button></div></article>)}</div></div>;
}
